DROP DATABASE IF EXISTS JC_PATHWAYS;
CREATE DATABASE JC_PATHWAYS DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE JC_PATHWAYS;

-- User information
--
CREATE TABLE Users (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  passwd CHAR(64) NOT NULL,
  salt CHAR(32) NOT NULL DEFAULT '',
  real_name VARCHAR(64) NOT NULL DEFAULT '',
  suspended TINYINT UNSIGNED NOT NULL DEFAULT 1,
  last_login_ts BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_ip VARCHAR(45) NULL DEFAULT NULL,
  type TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (username),
  UNIQUE (id),
  INDEX (type)
) ENGINE = InnoDB;

-- Session information
--
CREATE TABLE Sessions (
  uid INTEGER UNSIGNED NOT NULL,
  sid CHAR(32) NOT NULL,
  ts BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (uid) REFERENCES Users(id) ON DELETE CASCADE,
  UNIQUE (sid)
) ENGINE = InnoDB;